account/urls.py
from django.urls import path

from . import views

app_name="account"
urlpatterns=[

    path("login",views.UserLogin.as_view(),name="user_login"),
    path("register",views.OtpLoginView.as_view(),name="user_rejister"),
    path("add/address",views.AddAddressView.as_view(),name="add_address"),
]

cart/urls.py
from django.urls import path

from . import views

app_name="cart"
urlpatterns=[

    path("detail",views.CartDtailView.as_view(),name="cart_detail"),
    path("Add/<int:pk>",views.CartAddView.as_view(),name="cart_add"),
    path("delete/<str:id>",views.CartDeleteView.as_view(),name="cart_delete"),
    path("order/<int:pk>",views.OrderDetailView.as_view(),name="order_detail"),
    path("order/creat",views.OrderCreationView.as_view(),name="order_creation"),
    path("order/discount/<int:pk>",views.ApplyDiscountView.as_view(),name="discount_code"),

]

djangoProject_multishop/urls.py
from django.conf.urls.static import static
from django.contrib import admin

from django.urls import path,include

from djangoProject_multishop import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include("account.urls")),
    path("",include("home.urls")),
    path("products/",include("product.urls")),
    path("cart/",include("cart.urls")),
]
urlpatterns += static(settings.MEDIA_URL , document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models

# Create your models here.
from account.models import User
from product.models import Product


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="orders")
    created_at = models.DateTimeField(auto_now_add=True)
    total = models.IntegerField(default=0)
    is_paid = models.BooleanField(default=False)
    address=models.TextField(default="")

    def __str__(self):
        return self.user.phone


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name="items")
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name="items")
    size = models.CharField(max_length=12)
    color = models.CharField(max_length=12)
    quantity = models.SmallIntegerField(default=1)
    price = models.PositiveIntegerField()


class DiscountModel(models.Model):
    name = models.CharField(max_length=10,unique=True)
    percent = models.SmallIntegerField()
    quantity = models.IntegerField()

    def __str__(self):
        return self.name

cart/views.py
from django.shortcuts import render, redirect, get_list_or_404
from django.views import View
from .cart_module import Cart

# Create your views here.
from product.models import Product
from .models import Order, OrderItem, DiscountModel
from django.contrib.auth.mixins import LoginRequiredMixin


class CartDtailView(View):
    def get(self, request):
        cart = Cart(request)
        return render(request, "cart/cart.html", {"cart": cart})


class CartAddView(View):
    def post(self, request, pk):
        product = Product.objects.get(id=pk)
        size, color, quantity = request.POST.get("size"), request.POST.get("color"), request.POST.get("quantity")
        cart = Cart(request)
        cart.add(product, size, color, quantity)
        return redirect("cart:cart_detail")


class CartDeleteView(View):
    def get(self, request, id):
        cart = Cart(request)
        cart.delete(id)
        return redirect("cart:cart_detail")


class OrderDetailView(LoginRequiredMixin,View):
    def get(self, request, pk):
        order = Order.objects.get(id=pk)
        return render(request, "cart/order_detail.html", {"order": order})


class OrderCreationView(LoginRequiredMixin,View):
    def get(self, request):
        cart = Cart(request)
        order = Order.objects.create(user=request.user, total=cart.total())
        for item in cart:
            OrderItem.objects.create(order=order, product=item["product"], color=item["color"], size=item["size"]
                                     , quantity=item["quantity"], price=item["price"])

        cart.remove_cart()

        return redirect("cart:order_detail", order.id)


class ApplyDiscountView(LoginRequiredMixin,View):
    def post(self, request, pk):
        code = request.POST.get("discount_code")
        order = Order.objects.get(id=pk)
        discount_code = DiscountModel.objects.get(name=code)
        print(discount_code)

        if discount_code.quantity == 0:
            return redirect("cart:order_detail", order.id, {"error": "this code expied"})
        else:
            order.total -= discount_code.percent / 100 * order.total
            order.save()
            discount_code.quantity -= 1
            discount_code.save()
        return redirect("cart:order_detail", order.id)

cart/templates/cart/cart.html
{% extends "base.html" %}
{% load static %}

{% block content %}



    <!-- Cart Start -->
    <div class="container-fluid">
        <div class="row px-xl-5">
            <div class="col-lg-8 table-responsive mb-5">
                <table class="table table-light table-borderless table-hover text-center mb-0">
                    <thead class="thead-dark">
                        <tr>
                            <th>Image</th>
                            <th>Title</th>
                            <th>Price</th>
                            <th>Quantity</th>
                            <th>Color</th>
                            <th>Size</th>
                            <th>Total</th>
                            <th>Remove</th>
                        </tr>
                    </thead>
                    <tbody class="align-middle">
                        {% for i in cart  %}

                        <tr>
                            <td class="align-middle"><img src="{{  i.product.image.url }}" alt="" style="width: 50px;"> </td>
                            <td class="align-middle"> {{  i.product.title }}</td>
                            <td class="align-middle">{{  i.price }}</td>
                            <td class="align-middle">{{  i.quantity  }}</td>
                            <td class="align-middle">{{  i.color}}</td>
                            <td class="align-middle">{{  i.size }}</td>
                            <td class="align-middle">{{  i.total }}</td>
                            <td class="align-middle"><a href="{% url "cart:cart_delete" i.unique_id %}" class="btn btn-sm btn-danger"><i class="fa fa-times"></i></a></td>
                        </tr>

                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="col-lg-4">
                <form class="mb-30" action="">
                    <div class="input-group">
                        <input type="text" class="form-control border-0 p-4" placeholder="Coupon Code">
                        <div class="input-group-append">
                            <button class="btn btn-primary">Apply Coupon</button>
                        </div>
                    </div>
                </form>
                <h5 class="section-title position-relative text-uppercase mb-3"><span class="bg-secondary pr-3">Cart Summary</span></h5>
                <div class="bg-light p-30 mb-5">
                    <div class="border-bottom pb-2">
                        <div class="d-flex justify-content-between mb-3">
                            <h6>Subtotal</h6>
                            <h6>$150</h6>
                        </div>
                        <div class="d-flex justify-content-between">
                            <h6 class="font-weight-medium">Shipping</h6>
                            <h6 class="font-weight-medium">$10</h6>
                        </div>
                    </div>
                    <div class="pt-2">
                        <div class="d-flex justify-content-between mt-2">
                            <h5>Total</h5>
                            <h5>${{ cart.total }}</h5>
                        </div>
                        <a href="{% url "cart:order_creation" %}" class="btn btn-block btn-primary font-weight-bold my-3 py-3">Proceed To Checkout</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Cart End -->





    <!-- Back to Top -->
    <a href="#" class="btn btn-primary back-to-top"><i class="fa fa-angle-double-up"></i></a>



{% endblock %}

cart/templates/cart/order_detail.html
{% extends "base.html" %}
{% load static %}

{% block content %}

 <div class="container-fluid">
        <div class="row px-xl-5">
            <div class="col-lg-8 table-responsive mb-5">
                <table class="table table-light table-borderless table-hover text-center mb-0">
                    <thead class="thead-dark">
                        <tr>
                            <th>Image</th>
                            <th>Title</th>
                            <th>Price</th>
                            <th>Quantity</th>
                            <th>Color</th>
                            <th>Size</th>
                            <th>Total</th>

                        </tr>
                    </thead>
                    <tbody class="align-middle">
                        {% for i in order.items.all  %}

                        <tr>
                            <td class="align-middle"><img src="{{  i.product.image.url }}" alt="" style="width: 50px;"> </td>
                            <td class="align-middle"> {{  i.product.title }}</td>
                            <td class="align-middle">{{  i.price }}</td>
                            <td class="align-middle">{{  i.quantity  }}</td>
                            <td class="align-middle">{{  i.color}}</td>
                            <td class="align-middle">{{  i.size }}</td>
                            <td class="align-middle">{{  i.total }}</td>
                        </tr>

                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="col-lg-4">
                <form  method="post" class="mb-30"   action="{% url "cart:discount_code" order.id  %}">
                    {% csrf_token %}
                    <div class="input-group">
                        <input name="discount_code"  type="text" class="form-control border-0 p-4" placeholder="Discount Code">
                        <div class="input-group-append">
                            <button class="btn btn-primary">Apply Coupon</button>
                        </div>
                    </div>
                </form>
                <h5 class="section-title position-relative text-uppercase mb-3"><span class="bg-secondary pr-3">Cart Summary</span></h5>
                <div class="bg-light p-30 mb-5">
                    <div class="pt-2">
                        <div class="d-flex justify-content-between mt-2">
                            <h5>Total</h5>
                            <h5>${{ order.total }}</h5>
                        </div>

                    </div>
                </div>
             {% if request.user.addresses.all %}
                 <form method="post" href="{% url "send request in zarinpal " %}">
                <div class="dropdown">
                      <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Dropdown button
                      </button>
                      <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">

                              {% for i in request.user.addresses.all %}
                                <a class="dropdown-item" href="#">{{ i.address }}</a>
                              {% endfor %}
                      </div>
                </div>
                 <a  href="{% url "account:add_address"%}?next={% url "cart:order_detail" order.id %}"
                           class="btn btn-block btn-primary font-weight-bold my-3 py-3">Add new address</a>

                     <button type="submit"  class="btn btn-block btn-success font-weight-bold my-3 py-3">Pay</button>

                 </form>
            {% else %}
                 <a href="{% url "account:add_address"%}?next={% url "cart:order_detail" order.id %}"
                           class="btn btn-block btn-primary font-weight-bold my-3 py-3">Add address</a>

            {% endif %}
            </div>
        </div>
    </div>





{% endblock %}